### PR TITLE
Improve Release

### PR DESCRIPTION
**Pull request by stephencrowell**
Update README and make any other changes for extension release.

### CODE REVIEW

**Comment by stephencrowell** [comment]
For the README do we want more screenshots to help with the tutorial? Also do we need more detail on how to use the extension?

**Comment by ebrahimebrahim** [comment]
I like the breakdown of tutorial steps.

Yes, I think adding some small cropped screenshots to those could be helpful, though not a huge priority.
I might do it if I get a chance soon, adding some edits directly to this branch if you don't mind.

**Comment by ebrahimebrahim** [comment]
(This PR is tied to #26)

**Comment by ebrahimebrahim** [comment]
@stephencrowell On second thought let's go ahead and merge this! Since you are about to switch gears I think it will be easier to merge and have me iterate on it / add small screenshots in a separate PR later.

**Pull request merged**
